# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20170604_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='lastModifiedUser',
            field=models.CharField(default='', max_length=140),
        ),
    ]
