# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_camera_lastmodifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='lastModifiedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
