# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import filter.models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20170612_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='photo',
            field=models.ImageField(default='static/images/<built-in method now of type object at 0x9dab20>', upload_to=filter.models.renameToPrimaryKey),
        ),
    ]
