# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0008_auto_20170614_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='lastModifiedDate',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
