# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0009_auto_20170614_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='lastModifiedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
