# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import filter.models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0014_merge_20170621_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='photo',
            field=models.ImageField(default=b'static/images/<built-in method now of type object at 0x939c20>', upload_to=filter.models.renameToPrimaryKey, validators=[filter.models.validateFile]),
        ),
    ]
