# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0015_auto_20170621_2039'),
        ('filter', '0014_merge_20170621_1907'),
    ]

    operations = [
    ]
